### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by Glory-WF** [sometimesstudy/two-stage-MG#1]
你好！请问该程序有matlab版本吗？

**Comment by sometimesstudy** [comment]
没有matlab版本
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Tue, May 9, 2023 08:40 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: &nbsp;[sometimesstudy/two-stage-MG] 问题请教 (Issue #1)

&nbsp;



 
你好！请问该程序有matlab版本吗？
